/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifmg.edu.trabalho_java_avancado.visao;

import br.ifmg.edu.trabalho_java_avancado.modelo.Adm;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroAdm.CadastroAdmListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroMateria.CadastroMateriaListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroProdTerceiros.CadastroProdTercListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroVendedores.CadastroVendedorListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroFornecedor.CadastroFornecedorListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroProdProduzidos.CadastroProdProduzidosListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.Vendas.CadastroVendasListagem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author Vitor
 */
public class VisaoPrincipal_Adm extends javax.swing.JFrame {

    /**
     * Creates new form VisaoPrincipal
     */
    
    private Adm a;
    
    public VisaoPrincipal_Adm(Adm vendedor) {
        initComponents();
        
        this.a = vendedor;
        
        Timer timer = new Timer(1000,ativar);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblHora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuAdm = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jSubMenuAdm = new javax.swing.JMenuItem();
        jSubMenuFornecedor = new javax.swing.JMenuItem();
        jSubMenuVendedor = new javax.swing.JMenuItem();
        jSubMenuMateria = new javax.swing.JMenuItem();
        jSubMenuProdTerc = new javax.swing.JMenuItem();
        jSubMenuProdProduzido = new javax.swing.JMenuItem();
        jMenuProducao = new javax.swing.JMenu();
        jMenuVendas = new javax.swing.JMenu();
        jSubMenuVenda = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Padaria");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pao.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jlblHora.setText("xxxxxxx, dd/mm/yyyy 00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblHora)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlblHora)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel3.setText("Panificadora Chega Manteiga,Derrete!");
        jLabel3.setToolTipText("");

        jMenuCadastro.setText("Cadastros");

        jSubMenuAdm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuAdm.setText("Adminstradores");
        jSubMenuAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuAdmActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuAdm);

        jSubMenuFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuFornecedor.setText("Fornecedor");
        jSubMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuFornecedor);

        jSubMenuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuVendedor.setText("Funcionários");
        jSubMenuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuVendedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuVendedor);

        jSubMenuMateria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuMateria.setText("Matérias-Primas");
        jSubMenuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuMateriaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuMateria);

        jSubMenuProdTerc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuProdTerc.setText("Produtos Terceirizados");
        jSubMenuProdTerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuProdTercActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuProdTerc);

        jSubMenuProdProduzido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuProdProduzido.setText("Produtos Produzidos");
        jSubMenuProdProduzido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuProdProduzidoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuProdProduzido);

        jMenuAdm.add(jMenuCadastro);

        jMenuProducao.setText("Produção");
        jMenuAdm.add(jMenuProducao);

        jMenuVendas.setText("Vendas");

        jSubMenuVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuVenda.setText("Vendas");
        jSubMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuVendaActionPerformed(evt);
            }
        });
        jMenuVendas.add(jSubMenuVenda);

        jMenuAdm.add(jMenuVendas);

        jMenuRelatorios.setText("Relatórios");
        jMenuAdm.add(jMenuRelatorios);

        setJMenuBar(jMenuAdm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(756, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSubMenuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuVendedorActionPerformed
        // TODO add your handling code here:
        CadastroVendedorListagem dialog = new CadastroVendedorListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuVendedorActionPerformed

    private void jSubMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuFornecedorActionPerformed
        // TODO add your handling code here:
        CadastroFornecedorListagem dialog = new CadastroFornecedorListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuFornecedorActionPerformed

    private void jSubMenuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuMateriaActionPerformed
        // TODO add your handling code here:
        CadastroMateriaListagem dialog = new CadastroMateriaListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuMateriaActionPerformed

    private void jSubMenuProdTercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuProdTercActionPerformed
        // TODO add your handling code here:
        CadastroProdTercListagem dialog = new CadastroProdTercListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuProdTercActionPerformed

    private void jSubMenuAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuAdmActionPerformed
        // TODO add your handling code here:
        CadastroAdmListagem dialog = new CadastroAdmListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuAdmActionPerformed

    private void jSubMenuProdProduzidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuProdProduzidoActionPerformed
        // TODO add your handling code here:
        CadastroProdProduzidosListagem dialog = new CadastroProdProduzidosListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuProdProduzidoActionPerformed

    private void jSubMenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuVendaActionPerformed
        // TODO add your handling code here:
        CadastroVendasListagem dialog = new CadastroVendasListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoPrincipal_Adm().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuAdm;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuProducao;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jSubMenuAdm;
    private javax.swing.JMenuItem jSubMenuFornecedor;
    private javax.swing.JMenuItem jSubMenuMateria;
    private javax.swing.JMenuItem jSubMenuProdProduzido;
    private javax.swing.JMenuItem jSubMenuProdTerc;
    private javax.swing.JMenuItem jSubMenuVenda;
    private javax.swing.JMenuItem jSubMenuVendedor;
    private javax.swing.JLabel jlblHora;
    // End of variables declaration//GEN-END:variables
    
    ActionListener ativar = (
            new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Horas();
                }
            }            
        );
    
    
    private void Horas() {
            
        Calendar hora = Calendar.getInstance(getLocale());
        int hh = hora.get(Calendar.HOUR_OF_DAY);
        int mm = hora.get(Calendar.MINUTE);
        int ss = hora.get(Calendar.SECOND);

        int dia = hora.get(Calendar.DAY_OF_MONTH);
        int mes = hora.get(Calendar.MONTH);
        int ano = hora.get(Calendar.YEAR);

        int sem = hora.get(Calendar.DAY_OF_WEEK);
        String semana = "";
        switch (sem){
            case 0: semana = "Sábado";break;
            case 1: semana = "Domingo";break;
            case 2: semana = "Segunda-feira";break;
            case 3: semana = "Terça-feira";break;
            case 4: semana = "Quarta-feira";break;
            case 5: semana = "Quinta-feira";break;
            case 6: semana = "Sexta-feira";break;
        }

        jlblHora.setText(
          semana+", "+formatar(dia)+"/"+
                      formatar(++mes)+"/"+
                      formatar(ano)+" - Horas: "+
                      formatar(hh)+":"+
                      formatar(mm)+":"+
                      formatar(ss)
        );

    }
    
    private String formatar(int num){
        DecimalFormat df = new DecimalFormat("00");
        return df.format(num);
    }
}
