/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifmg.edu.trabalho_java_avancado.visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.Timer;

/**
 *
 * @author Vitor
 */
public class VisaoPrincipal_Vendedores extends javax.swing.JFrame {

    /**
     * Creates new form VisaoPrincipal
     */
    public VisaoPrincipal_Vendedores() {
        initComponents();
        
        Timer timer = new Timer(1000,ativar);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblHora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuAdm = new javax.swing.JMenuBar();
        jMenuVendasFunc = new javax.swing.JMenu();
        jSubMenuVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Padaria");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jlblHora.setText("xxxxxxx, dd/mm/yyyy 00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(570, Short.MAX_VALUE)
                .addComponent(jlblHora)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlblHora)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel3.setText("Panificadora Chega Manteiga,Derrete!");
        jLabel3.setToolTipText("");

        jMenuVendasFunc.setText("Vendas");

        jSubMenuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuVendas.setText("Vendas");
        jMenuVendasFunc.add(jSubMenuVendas);

        jMenuAdm.add(jMenuVendasFunc);

        setJMenuBar(jMenuAdm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(756, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    /*
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal_Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal_Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal_Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoPrincipal_Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoPrincipal_Vendedores().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuAdm;
    private javax.swing.JMenu jMenuVendasFunc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jSubMenuVendas;
    private javax.swing.JLabel jlblHora;
    // End of variables declaration//GEN-END:variables
    
    ActionListener ativar = (
            new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Horas();
                }
            }            
        );
    
    
    private void Horas() {
            
        Calendar hora = Calendar.getInstance();
        int hh = hora.get(Calendar.HOUR_OF_DAY);
        int mm = hora.get(Calendar.MINUTE);
        int ss = hora.get(Calendar.SECOND);

        int dia = hora.get(Calendar.DAY_OF_MONTH);
        int mes = hora.get(Calendar.MONTH);
        int ano = hora.get(Calendar.YEAR);

        int sem = hora.get(Calendar.DAY_OF_WEEK);
        String semana = "";
        switch (sem){
            case 0: semana = "Sábado";break;
            case 1: semana = "Domingo";break;
            case 2: semana = "Segunda-feira";break;
            case 3: semana = "Terça-feira";break;
            case 4: semana = "Quarta-feira";break;
            case 5: semana = "Quinta-feira";break;
            case 6: semana = "Sexta-feira";break;
        }

        jlblHora.setText(
          semana+", "+formatar(dia)+"/"+
                      formatar(++mes)+"/"+
                      formatar(ano)+" - Horas: "+
                      formatar(hh)+":"+
                      formatar(mm)+":"+
                      formatar(ss)
        );

    }
    
    private String formatar(int num){
        DecimalFormat df = new DecimalFormat("00");
        return df.format(num);
    }
}
